### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by crankycowboy** [AdamGit69/code-snippets#1]
Can you help with the difference between camera device id and camera feed entity?  I've tried multiple variations in those fields without luck

**Comment by AdamGit69** [comment]
In the automation, the device id is the physical camera and the entity ID, in this case is the motion alarm. Have you tried switching to Visual Editor as this makes it a lot easier to find the camera and then set the trigger as "motion alarm started detecting motion"??

Or you could make a new automation from scratch in visual editor, adding the camera and motion trigger as the "When" and then run the script in the "then do" section. 

You can also find your Enitity ID by going to: Settings>>Devices & Services >> Clicking on Entities up the top >> Selecting your camera device motion alarm >> then clicking on the little gear symbol. Entity ID should be in the 4th down drop down box.

To find the Device ID you go to: Settings>>Devices & Services >> Clicking on Devices up the top >> Selecting your camera and the device id should be in the URL up the top of your browser. I don't know any other ways to manually find.

Let me know if this helps! :)
